remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 

# Setup
title:  "Exploring Fictional Masculinity"             
tagline:             
description:         
url:     http://eng470-s23.github.io          
baseurl:   /chaserogers-repository/            
